"""PDF + DOCX report (CLAUDE.md Sec 6 Phase 5): every case, the plots, the
Monte Carlo, the ellipse, the compliance check, the assumptions with
their sources, and the validation section UP FRONT, worded per Sec 3.1's
rule (never "our RocketPy predicted 1,138" - the officials predicted it,
we independently replicate).
"""
import os

VALIDATION_SECTION_TEXT = """VALIDATION STATUS: PROVISIONAL

This report's numbers have NOT both passed the project's flight-data
validation tests (V1, V2) within the required +-5% tolerance - see below.
Per CLAUDE.md Rule 3, every result here must be read as provisional until
both pass.

V1 (2026-07-04, Pachuca profile): our independent replication predicts
1124.1 m AGL against the real flight's 1019.9 m AGL (telemetry) - an
error of +10.2%, outside the +-5% target. OpenRocket's own prediction for
this exact flight was 1027.2 m (-0.71% vs. the real flight) - a
materially closer match than ours, which is itself evidence of a real,
not-yet-isolated gap in this project's RocketPy translation (see the
code-to-code investigation in PROGRESS.md).

V2 (LASC 2026, Iacanga): our independent replication predicts 1196.9 m
AGL against the real flight's 1137 m AGL (SRAD telemetry) - an error of
+5.3%, just outside the +-5% target. At the Launch Readiness Review, LASC
officials independently re-simulated this same vehicle on-site with their
own inputs and predicted 1138 m (RocketPy, CRS 10.2.1) - within -0.09% of
the real flight. We did not reproduce the officials' exact inputs (we do
not have them) - this is an independent replication of the same vehicle,
not a claim that we matched their number.
"""


def _case_summary_lines(case_results):
    lines = []
    for name, r in case_results.items():
        if r.flight is None:
            lines.append(f"{name}: NOT BUILT - {r.warning}")
            continue
        env = r.flight.env
        apogee = r.flight.apogee - env.elevation
        line = f"{name}: apogee {apogee:.1f} m AGL, max speed {r.flight.max_speed:.1f} m/s, rail exit {r.flight.out_of_rail_velocity:.1f} m/s"
        if r.warning:
            line += f" -- WARNING: {r.warning}"
        lines.append(line)
    return lines


def generate_docx(output_path, mission_id, vehicle_name, case_results, compliance_rows, monte_carlo_result, assumptions):
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    doc.add_heading(f"Mission {mission_id} - {vehicle_name}", level=0)
    doc.add_paragraph("Generated by Beyond UP RocketPy")

    doc.add_heading("1. Validation status", level=1)
    for para in VALIDATION_SECTION_TEXT.strip().split("\n\n"):
        doc.add_paragraph(para)

    doc.add_heading("2. Flight cases", level=1)
    for line in _case_summary_lines(case_results):
        doc.add_paragraph(line, style="List Bullet")

    doc.add_heading("3. RCSM compliance", level=1)
    table = doc.add_table(rows=1, cols=4)
    hdr = table.rows[0].cells
    hdr[0].text, hdr[1].text, hdr[2].text, hdr[3].text = "Rule", "Check", "Status", "Detail"
    for rule_id, desc, status, detail in compliance_rows:
        row = table.add_row().cells
        row[0].text, row[1].text, row[2].text, row[3].text = rule_id, desc, status, detail

    doc.add_heading("4. Monte Carlo", level=1)
    if monte_carlo_result is not None:
        doc.add_paragraph(f"N = {monte_carlo_result.n_completed} completed ({monte_carlo_result.n_excluded} excluded)")
        doc.add_paragraph(f"Apogee: mean {monte_carlo_result.apogee_mean:.1f} m, 90% interval [{monte_carlo_result.apogee_p05:.1f}, {monte_carlo_result.apogee_p95:.1f}] m")
    else:
        doc.add_paragraph("Not run for this report.")

    doc.add_heading("5. Assumptions and sources", level=1)
    for a in assumptions:
        doc.add_paragraph(a, style="List Bullet")

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    doc.save(output_path)
    return output_path


def generate_pdf(output_path, mission_id, vehicle_name, case_results, compliance_rows, monte_carlo_result, assumptions):
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    styles = getSampleStyleSheet()
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    story = [Paragraph(f"Mission {mission_id} - {vehicle_name}", styles["Title"]), Spacer(1, 12)]

    story.append(Paragraph("1. Validation status (PROVISIONAL)", styles["Heading1"]))
    for para in VALIDATION_SECTION_TEXT.strip().split("\n\n"):
        story.append(Paragraph(para.replace("\n", " "), styles["BodyText"]))
        story.append(Spacer(1, 8))

    story.append(Paragraph("2. Flight cases", styles["Heading1"]))
    for line in _case_summary_lines(case_results):
        story.append(Paragraph(line, styles["BodyText"]))

    story.append(Paragraph("3. RCSM compliance", styles["Heading1"]))
    table_data = [["Rule", "Check", "Status", "Detail"]] + [list(row) for row in compliance_rows]
    t = Table(table_data, colWidths=[0.9 * inch, 2.3 * inch, 0.7 * inch, 2.3 * inch])
    t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#8A1538")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("GRID", (0, 0), (-1, -1), 0.5, colors.grey), ("FONTSIZE", (0, 0), (-1, -1), 8)]))
    story.append(t)

    story.append(Paragraph("4. Monte Carlo", styles["Heading1"]))
    if monte_carlo_result is not None:
        story.append(Paragraph(f"N = {monte_carlo_result.n_completed} completed ({monte_carlo_result.n_excluded} excluded)", styles["BodyText"]))
        story.append(Paragraph(f"Apogee: mean {monte_carlo_result.apogee_mean:.1f} m, 90% interval [{monte_carlo_result.apogee_p05:.1f}, {monte_carlo_result.apogee_p95:.1f}] m", styles["BodyText"]))
    else:
        story.append(Paragraph("Not run for this report.", styles["BodyText"]))

    story.append(Paragraph("5. Assumptions and sources", styles["Heading1"]))
    for a in assumptions:
        story.append(Paragraph("- " + a, styles["BodyText"]))

    doc.build(story)
    return output_path
