"""Exports a self-contained .py per RCSM case (CRS 10.1.3/10.1.5/10.1.6):
"a runnable .py or .ipynb" that "a RocketPy team member or LASC staff can
run on their own machine" with "just pip install rocketpy" - no import of
this repo's own stella_flight package. Every geometry/mass/motor/launch
value gets baked in as a literal in the generated file; only the .eng and
the two drag-curve CSVs stay as separate sibling files (CRS 10.1.9 wants
the .eng itself delivered anyway), referenced by relative path.

File name: Mission[ID]_[Case]_RocketPy_v[N].py (CRS 10.1.6).
"""
import math
import os


def _fmt(x):
    return repr(float(x))


def generate_case_script(mission_id, case_name, version, parsed, parsed_eng, eng_filename, power_off_drag_filename, power_on_drag_filename, dry_mass_kg, dry_cg_m, i_axial, i_transverse, radius_m, include_recovery, coordinate_system_orientation="tail_to_nose"):
    """Returns (filename, source_code). case_name is one of "Ballistic",
    "Nominal", "DrogueOnly", "MainAtApogee" (CRS 10.1.6/10.1.10-13)."""
    filename = f"Mission{mission_id}_{case_name}_RocketPy_v{version}.py"

    to_rpy_sign = -1.0 if coordinate_system_orientation == "tail_to_nose" else 1.0
    nose_pos = to_rpy_sign * 0.0
    motor_pos = to_rpy_sign * (parsed.body_tubes[-1].position_m + parsed.body_tubes[-1].length) if parsed.body_tubes else nose_pos
    cg_rpy = to_rpy_sign * dry_cg_m

    lines = []
    a = lines.append
    a(f'"""{filename}')
    a(f"Self-contained RocketPy simulation script - {case_name} case, Mission {mission_id}.")
    a("Generated by stella-flight (Stella Ignis / Beyond UP). Requires only:")
    a("    pip install rocketpy")
    a(f"Run alongside this file: {eng_filename}, {power_off_drag_filename}, {power_on_drag_filename}")
    a("")
    a("PROVISIONAL: see the source repo's PROGRESS.md for validation status")
    a("and every documented approximation (mass/CG source, drag curve source).")
    a('"""')
    a("import os")
    a("from rocketpy import Environment, SolidMotor, Rocket, Flight")
    a("")
    a("HERE = os.path.dirname(os.path.abspath(__file__))")
    a("")
    a("# --- Environment ---")
    a(f"env = Environment(latitude={_fmt(parsed.launch.latitude)}, longitude={_fmt(parsed.launch.longitude)}, elevation={_fmt(parsed.launch.altitude_m)})")
    a('env.set_atmospheric_model(type="standard_atmosphere")  # OpenRocket-recorded conditions - see PROGRESS.md; replace with real launch-day weather before submission')
    a("")
    a("# --- Motor (from the .eng file - see CRS 10.1.9) ---")
    h = parsed_eng.header
    a("motor = SolidMotor(")
    a('    thrust_source=os.path.join(HERE, "' + eng_filename + '"),')
    a(f"    dry_mass={_fmt(h.total_mass_kg - h.propellant_mass_kg)},")
    a("    dry_inertia=(0.01, 0.01, 0.001),  # not recoverable from a RASP .eng header - approximate, see reference/prometeo_mission44/src/prometeo/motor.py for the same convention")
    a(f"    nozzle_radius={_fmt((h.diameter_mm / 1000.0) * 0.15)},")
    a("    grain_number=1,")
    a("    grain_density=1750.0,")
    a(f"    grain_outer_radius={_fmt((h.diameter_mm / 1000.0) / 2.0 * 0.95)},")
    a(f"    grain_initial_inner_radius={_fmt((h.diameter_mm / 1000.0) / 2.0 * 0.25)},")
    a(f"    grain_initial_height={_fmt((h.length_mm / 1000.0) * 0.9)},")
    a("    grain_separation=0.005,")
    a(f"    grains_center_of_mass_position={_fmt((h.length_mm / 1000.0) / 2.0)},")
    a(f"    center_of_dry_mass_position={_fmt((h.length_mm / 1000.0) / 2.0)},")
    a("    nozzle_position=0,")
    a(f"    burn_time={_fmt(parsed_eng.burn_time_s)},")
    a(f"    throat_radius={_fmt((h.diameter_mm / 1000.0) * 0.1)},")
    a('    coordinate_system_orientation="nozzle_to_combustion_chamber",')
    a(")")
    a("")
    a("# --- Rocket (dry mass/CG/inertia - see PROGRESS.md for source: override vs geometric estimate) ---")
    a("rocket = Rocket(")
    a(f"    radius={_fmt(radius_m)},")
    a(f"    mass={_fmt(dry_mass_kg)},")
    a(f"    inertia=({_fmt(i_transverse)}, {_fmt(i_transverse)}, {_fmt(i_axial)}),")
    a('    power_off_drag=os.path.join(HERE, "' + power_off_drag_filename + '"),')
    a('    power_on_drag=os.path.join(HERE, "' + power_on_drag_filename + '"),')
    a(f"    center_of_mass_without_motor={_fmt(cg_rpy)},")
    a(f'    coordinate_system_orientation="{coordinate_system_orientation}",')
    a(")")
    a(f"rocket.add_motor(motor, position={_fmt(motor_pos)})")
    a("")
    if parsed.nose is not None:
        from stella_flight.translate import rocketpy_nose_kind
        a(f'rocket.add_nose(length={_fmt(parsed.nose.length)}, kind="{rocketpy_nose_kind(parsed.nose.shape)}", position={_fmt(nose_pos)})')
    for fin in parsed.fins:
        a("rocket.add_trapezoidal_fins(")
        a(f"    n={fin.count}, root_chord={_fmt(fin.root_chord)}, tip_chord={_fmt(fin.tip_chord)},")
        a(f"    span={_fmt(fin.span)}, sweep_length={_fmt(fin.sweep_length)}, cant_angle={_fmt(fin.cant_angle)},")
        a(f"    position={_fmt(to_rpy_sign * fin.position_m)},")
        a(")")
    if parsed.rail_buttons is not None:
        a(f"rocket.set_rail_buttons(upper_button_position={_fmt(to_rpy_sign * parsed.rail_buttons.upper_position_m)}, lower_button_position={_fmt(to_rpy_sign * parsed.rail_buttons.lower_position_m)})")
    a("")
    if include_recovery:
        a("# --- Recovery (CRS 10.1.9: trigger, phase, size, Cd) ---")
        for chute in parsed.parachutes:
            if chute.cd is None:
                a(f"# SKIPPED parachute {chute.name!r}: Cd was 'auto' in OpenRocket, not resolvable from the .ork file - add it manually")
                continue
            cd_s = chute.cd * math.pi * (chute.diameter / 2.0) ** 2
            trigger = '"apogee"' if chute.deploy_event == "apogee" else _fmt(chute.deploy_altitude)
            a(f'rocket.add_parachute(name="{chute.name}", cd_s={_fmt(cd_s)}, trigger={trigger}, sampling_rate=100, lag={_fmt(chute.deploy_delay)})')
    else:
        a("# --- Recovery: NONE (Ballistic case, CRS 10.1.11 - free-fall under drag alone) ---")
    a("")
    a("# --- Launch conditions (CRS 10.1.8) ---")
    a("flight = Flight(")
    a("    rocket=rocket,")
    a("    environment=env,")
    a(f"    rail_length={_fmt(parsed.launch.rail_length_m)},")
    a(f"    inclination={_fmt(parsed.launch.inclination_deg)},")
    a(f"    heading={_fmt(parsed.launch.rail_direction_deg)},")
    a(")")
    a("")
    a("if __name__ == '__main__':")
    a("    flight.info()")
    a('    print(f"Apogee AGL: {flight.apogee - env.elevation:.1f} m")')
    a('    print(f"Max speed: {flight.max_speed:.1f} m/s")')
    a('    print(f"Rail exit velocity: {flight.out_of_rail_velocity:.1f} m/s")')

    return filename, "\n".join(lines) + "\n"
